export const SOURCE_MILES = [
  "Aeromexico",
  "Air Canada Aeroplan",
  "Air France/KLM Flying Blue",
  "Alaska Mileage Plan",
  "American Airlines",
  "Azul Fidelidade",
  "Copa ConnectMiles",
  "Delta SkyMiles",
  "Emirates Skywards",
  "Ethiopian ShebaMiles",
  "Etihad Guest",
  "GOL Smiles",
  "JetBlue TrueBlue",
  "Lufthansa Miles & More",
  "Qantas Frequent Flyer",
  "Qatar Airways Privilege Club",
  "SAS EuroBonus",
  "Saudia AlFursan",
  "Singapore Airlines KrisFlyer",
  "Turkish Miles&Smiles",
  "United MileagePlus",
  "Virgin Atlantic",
  "Virgin Australia Velocity",
]